apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator-peer
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.69.1
  name: prometheus-operator-peer
  namespace: observability-peer
