apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator-peer
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.77.1
  name: prometheus-operator-peer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-peer
subjects:
- kind: ServiceAccount
  name: prometheus-operator-peer
  namespace: observability-peer
